use techlabs;


-- CREATE TABLE BANK_MASTER AND BANK_TRANSACTION
CREATE TABLE `customer`(`NAME` VARCHAR(30) NOT NULL, `BALANCE` FLOAT);
CREATE TABLE `merchant`(`NAME` VARCHAR(30) NOT NULL, `BALANCE` FLOAT);


DROP TRIGGER IF EXISTS `CHECK_MIN_BALANCE_LIMIT`;

-- CREATE TRIGGER FOR CHECK BALANCE LIMIT
DELIMITER $$
CREATE DEFINER=`root`@`localhost` TRIGGER `CHECK_MIN_BALANCE_LIMIT` 
BEFORE UPDATE 
ON `customer` 
FOR EACH ROW 
BEGIN 
    IF BALANCE<1000 
    THEN 
        SIGNAL SQLSTATE '50001' 
        SET MESSAGE_TEXT = 'check constraint on customer.balance failed!';
    END IF;
END$$
DELIMITER ;