use aurionpro;
 
ALTER TABLE EMP
DROP CONSTRAINT EMP_SELF_KEY;

ALTER TABLE EMP
DROP CONSTRAINT EMP_PRIMARY_KEY;

CREATE NONCLUSTERED INDEX NON_CLUSTERED_INDEX_NAME
ON EMP(ENAME ASC);

EXECUTE sp_helpindex EMP;

SELECT * FROM EMP WHERE ENAME LIKE 's%';

DROP INDEX NON_CLUSTERED_INDEX_NAME ON EMP;


ALTER TABLE EMP
ADD CONSTRAINT EMP_PRIMARY_KEY PRIMARY KEY (EMPNO);

ALTER TABLE EMP
ADD CONSTRAINT EMP_SELF_KEY FOREIGN KEY (MGR) REFERENCES EMP(EMPNO);