-- DEPTWISE, JOBWISE SUM OF THE SALARY OF THE EMPLOYEE WHOS SALARY GREATER THAN 2000 
-- AND DISPLAY IN  THE ORDER OF THE SUM OF THE SALARY

SELECT DNAME, JOB, SUM(SAL) AS TTLSAL
FROM EMP E
JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY DNAME, JOB
HAVING SUM(SAL)>=2000
ORDER BY TTLSAL;