USE aurionpro;
GO

create schema aurionpro
--CREATE PROCEDURE TO GIVE A HIKE TO PRATICULAR EMPLOYEE
CREATE PROCEDURE giveHike
(
	@EMPNO INT,
	@PERCENTAGE FLOAT
)
AS
IF EXISTS(SELECT 1 FROM EMP WHERE EMPNO=@EMPNO)
	BEGIN
		UPDATE EMP
		SET SAL=SAL+SAL*(@PERCENTAGE/100)
		WHERE EMPNO=@EMPNO;
	END
ELSE
	BEGIN
		PRINT 'EMPLOYEE NOT EXIST'
	END
GO

-- TESTING
BEGIN TRANSACTION
SELECT * FROM EMP WHERE EMPNO=7839;
EXEC giveHike 782339, 10 ;
SELECT * FROM EMP WHERE EMPNO=7839;
ROLLBACK