use aurionpro;

-- CREATE SCHEMA TO USE FUNCTION WITH A SCHEMA NAME
GO
CREATE SCHEMA aurionpro;

--CREATE FUNCTION TO FORMAT CURRENT DATE
GO
CREATE FUNCTION aurionpro.getCurrentDate()
RETURNS VARCHAR(8)
AS 
BEGIN 
DECLARE @RETURN VARCHAR(8)
SET @RETURN = CONVERT(VARCHAR, GETDATE(), 112)
return @RETURN
END

-- FINALLY THE FUCTION CALL TO GET FORMATED CURRENT DATE
SELECT aurionpro.getCurrentDate() AS FORMATED_CUR_DATE;