USE india;

-- DISPLAY REGIONSWISE COUNTRY 
SELECT REGION_NAME, COUNTRY_NAME
FROM REGIONS R
JOIN COUNTRIES C
ON R.REGION_ID=C.REGION_ID
ORDER BY REGION_NAME, COUNTRY_NAME ASC;

-- DISPLAY COUNTRYWISE LOCATION
SELECT COUNTRY_NAME, CITY, STREET_ADDRESS, POSTAL_CODE
FROM COUNTRIES C
JOIN LOCATIONS L
ON C.COUNTRY_ID=L.COUNTRY_ID
ORDER BY COUNTRY_NAME,CITY,POSTAL_CODE ASC;

-- DISPLAY ALL REGIONS WHICH DOESNT HAVE ANY COUNTRY
SELECT REGION_NAME
FROM REGIONS R
LEFT JOIN COUNTRIES C
ON R.REGION_ID=C.REGION_ID
WHERE C.REGION_ID IS NULL
ORDER BY REGION_NAME ASC;


-- DISPLAY COUNTRIES WHICH DOESNT HAVE ANY LOCATION
SELECT COUNTRY_NAME
FROM COUNTRIES C
LEFT JOIN LOCATIONS L
ON C.COUNTRY_ID=L.COUNTRY_ID
WHERE L.COUNTRY_ID IS NULL
ORDER BY COUNTRY_NAME,CITY,POSTAL_CODE ASC;

-- DISPLAY ALL COUNTRY NAME AND THEIR REGION NAME
SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES C
LEFT JOIN REGIONS R
ON R.REGION_ID=C.REGION_ID
ORDER BY COUNTRY_NAME, REGION_NAME ASC;

-- DISPLAY ALL COUNTRY NAME AND REGION AND LOCATION NAME
SELECT CITY, COUNTRY_NAME, REGION_NAME
FROM LOCATIONS L
LEFT OUTER JOIN COUNTRIES C
ON L.COUNTRY_ID=C.COUNTRY_ID
LEFT OUTER JOIN REGIONS R
ON R.REGION_ID=C.REGION_ID
ORDER BY CITY, COUNTRY_NAME, REGION_NAME ASC;

-- INSERT MUMBAI INTO LOCATION ADDRESS SWABHAV
-- INSERT INTO locations VALUES( 2000, 'B-2 LARAM-CENTER', '400068', 'Mumbai', '', 'IN');

-- DISPLAY FULL ADDRESS OF SWABHAV LAB
SELECT STREET_ADDRESS,CITY,POSTAL_CODE, COUNTRY_NAME, REGION_NAME
FROM LOCATIONS L
JOIN COUNTRIES C
ON L.COUNTRY_ID=C.COUNTRY_ID
JOIN REGIONS R
ON R.REGION_ID=C.REGION_ID
WHERE LOCATION_ID=2000;